### ISSUE TITLE
Superseded project?

### ISSUE THREAD

**Issue by robertoaloi** [aws-beam/aws-erlang-metadata#3]
Hi @mrallen1 and @jkakar 

Do I understand correctly that this repo is superseded by `aws_credentials`?

**Comment by jadeallenx** [comment]
That was the intention, yes. As you know old Erlang projects never really die, they just sort of bit rot into oblivion. 😬

**Comment by robertoaloi** [comment]
Should we archive/delete the repo, then? It would be nice not to create confusion among users...

**Comment by jadeallenx** [comment]
Yeah it probably should be archived, but I'm sure it's still in people's rebar.config or dependency paths. So I think deleting it would be quite rude.

**Comment by robertoaloi** [comment]
Fair point. So let's archive it and change its README to point to the new repo, instead.

**Comment by jadeallenx** [comment]
👍
